# Generated by Django 5.2.6 on 2025-09-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='entreprises/profiles/'),
        ),
    ]
