# Generated by Django 5.2.6 on 2025-09-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Freelance',
            fields=[
                ('id_freelance', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('competence', models.TextField()),
                ('experience', models.TextField()),
                ('formation', models.TextField()),
                ('certificat', models.TextField(blank=True, null=True)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(upload_to='freelance_photos/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='freelance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
