# Generated by Django 5.2.6 on 2025-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0002_freelance_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='freelance_photos/'),
        ),
    ]
