# Generated by Django 5.2.6 on 2025-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('entreprise', 'Entreprise'), ('freelance', 'Freelance')], max_length=20, verbose_name='Rôle'),
        ),
    ]
