# Generated by Django 5.2.6 on 2025-09-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_remove_user_nom_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Entreprise', 'Entreprise'), ('Freelance', 'Freelance')], max_length=20, verbose_name='Rôle'),
        ),
    ]
