# Generated by Django 5.2.6 on 2025-09-28 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelance', '0003_alter_freelance_photo'),
        ('mission', '0002_alter_mission_entreprise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_candidature', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('recommandee', 'Recommandée'), ('en_entretien', 'En entretien'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('date_entretien', models.DateTimeField(blank=True, null=True)),
                ('commentaire_entretien', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('freelance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='freelance.freelance')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='mission.mission')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('mission', 'freelance'), name='unique_candidature')],
            },
        ),
    ]
