# Generated by Django 5.2.6 on 2025-09-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('recommandee', 'Recommandée'), ('en_entretien', 'En entretien'), ('refusee', 'Refusée')], default='en_attente', max_length=20),
        ),
    ]
