# Generated by Django 5.2.6 on 2025-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0003_alter_candidature_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, default='timezone.now', null=True),
        ),
    ]
