# Generated by Django 5.2.6 on 2025-10-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidature', '0004_candidature_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
