# Generated by Django 5.2.6 on 2025-09-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entreprise', '0002_entreprise_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id_mission', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('competence_requis', models.TextField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='entreprise.entreprise')),
            ],
        ),
    ]
